name: 测试

permissions:
  contents: write
  discussions: write

on:
  push:
    branches:
      - main
    paths-ignore: # 这里表示忽略的文件或目录，不会触发流程
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
      - '.npmrc'

jobs:
  upload:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.0'
          cache: 'npm'
          # architecture: 'x64'

      - run: npm i
      - run: npm run build:exe

      - name: Install UPX
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: upx windows
        if: matrix.os == 'windows-latest'
        run: upx -9 ./dist/twikoo-win.exe

      - name: upx macos
        if: matrix.os == 'macos-13'
        run: |
          brew install upx
          upx -9 ./dist/twikoo-macos

      - name: gzexe linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          gzexe ./dist/twikoo-linux
          rm -rf ./dist/twikoo-linux~

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: twikoo-${{ matrix.os }}
          path: dist/
          compression-level: 9 # 压缩等级 默认 6
          retention-days: 1 # 保留天数
